"""
Ride-Sharing Analytics Dashboard
---------------------------------
Single-file Streamlit app. Data lives in an editable spreadsheet-style
grid (the "Edit Data" tab) — no code editing needed to change names,
fares, cities, etc. Every chart and KPI recalculates live as soon as
you edit a cell — no "Apply" button required.
"""

import os
import sqlite3
import pandas as pd
import requests
import streamlit as st

st.set_page_config(page_title="Ride-Sharing Analytics", page_icon="🚖", layout="wide")

# ------------------------------------------------------------------
# Groq chat helper — used by the "Ask the Data" tab. Free API key
# from console.groq.com, stored as GROQ_API_KEY in Streamlit secrets.
# ------------------------------------------------------------------
GROQ_MODEL = "openai/gpt-oss-120b"  # current Groq-recommended general model; change here if retired


def call_groq(messages, temperature=0.3):
    api_key = st.secrets.get("GROQ_API_KEY")
    if not api_key:
        return None, (
            "No GROQ_API_KEY found in Streamlit secrets. Get a free key at "
            "console.groq.com, then add it under Settings → Secrets in the "
            "Streamlit Cloud dashboard as:\n\nGROQ_API_KEY = \"your-key-here\""
        )
    try:
        resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={"model": GROQ_MODEL, "messages": messages, "temperature": temperature},
            timeout=30,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"], None
    except requests.exceptions.HTTPError as e:
        return None, f"Groq API error ({resp.status_code}): {resp.text[:300]}"
    except Exception as e:
        return None, f"Request to Groq failed: {e}"

# ------------------------------------------------------------------
# 1. Default seed data — loaded from the bundled CSVs (500 trips /
#    40 riders / 18 drivers, generated by generate_data.py). Falls
#    back to a small inline sample if the CSVs aren't present, so the
#    app still runs even if only app.py gets copied somewhere.
# ------------------------------------------------------------------
APP_DIR = os.path.dirname(os.path.abspath(__file__))


def _load_default(csv_name, fallback_rows, columns):
    path = os.path.join(APP_DIR, csv_name)
    if os.path.exists(path):
        return pd.read_csv(path)
    return pd.DataFrame(fallback_rows, columns=columns)


DEFAULT_RIDERS = _load_default(
    "riders_data.csv",
    [(1, 'Rahul', 'Mumbai', '2024-01-10'), (2, 'Priya', 'Delhi', '2024-02-15')],
    ["rider_id", "rider_name", "city", "signup_date"],
)
DEFAULT_DRIVERS = _load_default(
    "drivers_data.csv",
    [(101, 'Arjun', 'Sedan', 'Mumbai', '2023-05-10')],
    ["driver_id", "driver_name", "vehicle_type", "city", "joining_date"],
)
DEFAULT_TRIPS = _load_default(
    "trips_data.csv",
    [(1001, 1, 101, '2025-01-05 09:15:00', 'Andheri', 'Bandra', 12.5, 420, 'Completed', 'UPI')],
    ["trip_id", "rider_id", "driver_id", "trip_date", "pickup_location",
     "drop_location", "distance_km", "fare", "trip_status", "payment_method"],
)

# ------------------------------------------------------------------
# 2. Session state holds the *editable* copies of each table
# ------------------------------------------------------------------
if "riders_df" not in st.session_state:
    st.session_state.riders_df = DEFAULT_RIDERS.copy()
if "drivers_df" not in st.session_state:
    st.session_state.drivers_df = DEFAULT_DRIVERS.copy()
if "trips_df" not in st.session_state:
    st.session_state.trips_df = DEFAULT_TRIPS.copy()


def build_connection(riders_df, drivers_df, trips_df):
    """Rebuild a fresh in-memory SQLite DB from the current edited data."""
    conn = sqlite3.connect(":memory:", check_same_thread=False)
    riders_df.to_sql("riders", conn, index=False, if_exists="replace")
    drivers_df.to_sql("drivers", conn, index=False, if_exists="replace")
    trips_df.to_sql("trips", conn, index=False, if_exists="replace")
    return conn


def q(conn, sql, params=None):
    return pd.read_sql_query(sql, conn, params=params)


# ------------------------------------------------------------------
# 3. Page skeleton — title/caption first, then a placeholder for the
#    KPI row (filled in AFTER we've read this run's edits, further
#    down), then the tabs. Using a placeholder lets the KPI row stay
#    visually at the top while still reflecting the latest edits.
# ------------------------------------------------------------------
st.title("🚖 Ride-Sharing Analytics Dashboard")
st.caption("Edit data in the ✏️ Edit Data tab — every chart and KPI updates live as you type.")
kpi_placeholder = st.container()
st.divider()

(tab_edit, tab_revenue, tab_drivers, tab_riders, tab_time, tab_routes,
 tab_trends, tab_insights, tab_chat, tab_raw) = st.tabs(
    ["✏️ Edit Data", "💰 Revenue", "🚗 Drivers", "🧍 Riders", "⏰ Peak Times",
     "📍 Routes", "📈 Trends", "🔍 Insights", "💬 Ask the Data", "🗄️ Raw SQL"]
)

# ------------------------------------------------------------------
# 4. Edit Data tab — rendered FIRST in code (even though it's a tab),
#    so st.session_state is updated with this run's edits before we
#    build the SQLite connection and compute KPIs below.
# ------------------------------------------------------------------
with tab_edit:
    st.subheader("Riders")
    st.caption("Edit any cell directly. Click the blank bottom row to add a new rider.")
    edited_riders = st.data_editor(
        st.session_state.riders_df, num_rows="dynamic", use_container_width=True,
        key="riders_editor",
        column_config={
            "rider_id": st.column_config.NumberColumn("Rider ID", required=True),
            "rider_name": st.column_config.TextColumn("Name", required=True),
            "city": st.column_config.TextColumn("City"),
            "signup_date": st.column_config.TextColumn("Signup Date (YYYY-MM-DD)"),
        },
    )

    st.subheader("Drivers")
    edited_drivers = st.data_editor(
        st.session_state.drivers_df, num_rows="dynamic", use_container_width=True,
        key="drivers_editor",
        column_config={
            "driver_id": st.column_config.NumberColumn("Driver ID", required=True),
            "driver_name": st.column_config.TextColumn("Name", required=True),
            "vehicle_type": st.column_config.SelectboxColumn(
                "Vehicle Type", options=["Sedan", "SUV", "Bike", "Auto", "Mini"], required=True
            ),
            "city": st.column_config.TextColumn("City"),
            "joining_date": st.column_config.TextColumn("Joining Date (YYYY-MM-DD)"),
        },
    )

    st.subheader("Trips")
    st.caption(
        "rider_id and driver_id must match the tables above. "
        "trip_status must be exactly 'Completed' or 'Cancelled'."
    )
    edited_trips = st.data_editor(
        st.session_state.trips_df, num_rows="dynamic", use_container_width=True,
        key="trips_editor",
        column_config={
            "trip_id": st.column_config.NumberColumn("Trip ID", required=True),
            "rider_id": st.column_config.NumberColumn("Rider ID", required=True),
            "driver_id": st.column_config.NumberColumn("Driver ID", required=True),
            "trip_date": st.column_config.TextColumn("Trip Date/Time (YYYY-MM-DD HH:MM:SS)"),
            "pickup_location": st.column_config.TextColumn("Pickup"),
            "drop_location": st.column_config.TextColumn("Drop"),
            "distance_km": st.column_config.NumberColumn("Distance (km)", format="%.1f"),
            "fare": st.column_config.NumberColumn("Fare (₹)", format="%.0f"),
            "trip_status": st.column_config.SelectboxColumn(
                "Status", options=["Completed", "Cancelled"], required=True
            ),
            "payment_method": st.column_config.SelectboxColumn(
                "Payment", options=["UPI", "Card", "Cash"], required=True
            ),
        },
    )

    # Sync every edit straight into session_state immediately — no button needed.
    st.session_state.riders_df = edited_riders
    st.session_state.drivers_df = edited_drivers
    st.session_state.trips_df = edited_trips

    if st.button("↩️ Reset to sample data"):
        st.session_state.riders_df = DEFAULT_RIDERS.copy()
        st.session_state.drivers_df = DEFAULT_DRIVERS.copy()
        st.session_state.trips_df = DEFAULT_TRIPS.copy()
        st.rerun()

# ------------------------------------------------------------------
# 5. Build the DB from THIS run's (possibly just-edited) data, then
#    fill in the KPI placeholder from step 3.
# ------------------------------------------------------------------
conn = build_connection(
    st.session_state.riders_df, st.session_state.drivers_df, st.session_state.trips_df
)

trip_count = q(conn, "SELECT COUNT(*) AS n FROM trips").iloc[0]["n"]

with kpi_placeholder:
    if trip_count == 0:
        st.warning("No trips in the data yet — add some rows in the ✏️ Edit Data tab.")
    else:
        summary = q(conn, """
            SELECT
                COUNT(*) AS total_trips,
                SUM(CASE WHEN trip_status = 'Completed' THEN 1 ELSE 0 END) AS completed_trips,
                SUM(CASE WHEN trip_status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_trips,
                SUM(CASE WHEN trip_status = 'Completed' THEN fare ELSE 0 END) AS total_revenue,
                ROUND(AVG(CASE WHEN trip_status = 'Completed' THEN fare END), 2) AS avg_fare,
                ROUND(AVG(CASE WHEN trip_status = 'Completed' THEN distance_km END), 2) AS avg_distance
            FROM trips
        """).iloc[0]

        cancel_rate = round(100 * summary["cancelled_trips"] / summary["total_trips"], 1)
        completed = summary["completed_trips"] or 0
        avg_distance = summary["avg_distance"] or 0
        fare_per_km = (
            round(summary["total_revenue"] / (avg_distance * completed), 2)
            if completed and avg_distance else 0
        )

        c1, c2, c3, c4, c5 = st.columns(5)
        c1.metric("Total Trips", int(summary["total_trips"]))
        c2.metric("Completed", int(completed))
        c3.metric("Cancellation Rate", f"{cancel_rate}%")
        c4.metric("Total Revenue", f"₹{summary['total_revenue']:,.0f}")
        c5.metric("Avg Fare / km", f"₹{fare_per_km}")

if trip_count == 0:
    st.stop()

# ------------------------------------------------------------------
# 6. Remaining tabs — all read from the same up-to-date `conn`.
# ------------------------------------------------------------------
with tab_revenue:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Revenue by City")
        rev_city = q(conn, """
            SELECT d.city, SUM(t.fare) AS revenue
            FROM trips t JOIN drivers d ON t.driver_id = d.driver_id
            WHERE t.trip_status = 'Completed'
            GROUP BY d.city ORDER BY revenue DESC
        """)
        if not rev_city.empty:
            st.bar_chart(rev_city.set_index("city"))
        else:
            st.info("No completed trips yet.")

    with col2:
        st.subheader("Revenue by Vehicle Type")
        rev_vehicle = q(conn, """
            SELECT d.vehicle_type, SUM(t.fare) AS revenue
            FROM trips t JOIN drivers d ON t.driver_id = d.driver_id
            WHERE t.trip_status = 'Completed'
            GROUP BY d.vehicle_type ORDER BY revenue DESC
        """)
        if not rev_vehicle.empty:
            st.bar_chart(rev_vehicle.set_index("vehicle_type"))

    st.subheader("Payment Method Distribution")
    pay = q(conn, "SELECT payment_method, COUNT(*) AS trips FROM trips GROUP BY payment_method")
    st.bar_chart(pay.set_index("payment_method"))

with tab_drivers:
    st.subheader("Driver Earnings & Trip Counts")
    driver_stats = q(conn, """
        SELECT d.driver_name, d.city, d.vehicle_type,
               COUNT(*) AS total_trips,
               SUM(CASE WHEN t.trip_status = 'Completed' THEN 1 ELSE 0 END) AS completed_trips,
               SUM(CASE WHEN t.trip_status = 'Completed' THEN t.fare ELSE 0 END) AS earnings
        FROM trips t JOIN drivers d ON t.driver_id = d.driver_id
        GROUP BY d.driver_name, d.city, d.vehicle_type
        ORDER BY earnings DESC
    """)
    st.dataframe(driver_stats, use_container_width=True, hide_index=True)
    if not driver_stats.empty:
        st.bar_chart(driver_stats.set_index("driver_name")["earnings"])

    st.subheader("Driver Utilization Rate")
    util = q(conn, """
        WITH dc AS (
            SELECT driver_id, COUNT(*) AS completed_trips
            FROM trips WHERE trip_status='Completed' GROUP BY driver_id
        )
        SELECT d.driver_name, dc.completed_trips,
               ROUND(100.0 * dc.completed_trips / (SELECT SUM(completed_trips) FROM dc), 1) AS utilization_pct
        FROM dc JOIN drivers d ON dc.driver_id = d.driver_id
        ORDER BY utilization_pct DESC
    """)
    st.dataframe(util, use_container_width=True, hide_index=True)

with tab_riders:
    st.subheader("Most Active Riders")
    rider_stats = q(conn, """
        SELECT r.rider_name, r.city,
               COUNT(*) AS total_trips,
               SUM(CASE WHEN t.trip_status = 'Completed' THEN t.fare ELSE 0 END) AS total_spend
        FROM trips t JOIN riders r ON t.rider_id = r.rider_id
        GROUP BY r.rider_name, r.city
        ORDER BY total_trips DESC, total_spend DESC
    """)
    st.dataframe(rider_stats, use_container_width=True, hide_index=True)

    retention_df = q(conn, """
        WITH rc AS (
            SELECT rider_id, COUNT(*) AS completed_trips
            FROM trips WHERE trip_status='Completed' GROUP BY rider_id
        )
        SELECT ROUND(100.0 * SUM(CASE WHEN completed_trips > 1 THEN 1 ELSE 0 END) / COUNT(*), 1) AS retention_pct
        FROM rc
    """)
    retention = retention_df.iloc[0]["retention_pct"] if not retention_df.empty else 0
    st.metric("Rider Retention Rate", f"{retention}%")

with tab_time:
    st.subheader("Peak Booking Hour")
    hours = q(conn, """
        SELECT CAST(strftime('%H', trip_date) AS INTEGER) AS hour, COUNT(*) AS trips
        FROM trips GROUP BY hour ORDER BY hour
    """)
    if not hours.empty:
        st.bar_chart(hours.set_index("hour"))

    st.subheader("Peak Booking Day")
    days = q(conn, """
        SELECT strftime('%w', trip_date) AS dow, COUNT(*) AS trips
        FROM trips GROUP BY dow ORDER BY dow
    """)
    if not days.empty:
        day_names = {"0": "Sun", "1": "Mon", "2": "Tue", "3": "Wed", "4": "Thu", "5": "Fri", "6": "Sat"}
        days["day"] = days["dow"].map(day_names)
        st.bar_chart(days.set_index("day")["trips"])

with tab_routes:
    st.subheader("Highest Revenue Routes")
    routes = q(conn, """
        SELECT pickup_location, drop_location, COUNT(*) AS trips, SUM(fare) AS revenue
        FROM trips WHERE trip_status='Completed'
        GROUP BY pickup_location, drop_location
        ORDER BY revenue DESC
    """)
    st.dataframe(routes, use_container_width=True, hide_index=True)

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Top Pickup Locations")
        pu = q(conn, "SELECT pickup_location, COUNT(*) AS trips FROM trips GROUP BY pickup_location ORDER BY trips DESC")
        if not pu.empty:
            st.bar_chart(pu.set_index("pickup_location"))
    with col2:
        st.subheader("Top Drop Locations")
        do = q(conn, "SELECT drop_location, COUNT(*) AS trips FROM trips GROUP BY drop_location ORDER BY trips DESC")
        if not do.empty:
            st.bar_chart(do.set_index("drop_location"))

with tab_trends:
    st.subheader("Monthly Revenue & Trip Volume")
    monthly = q(conn, """
        SELECT strftime('%Y-%m', trip_date) AS month,
               SUM(CASE WHEN trip_status='Completed' THEN fare ELSE 0 END) AS revenue,
               COUNT(*) AS total_trips
        FROM trips GROUP BY month ORDER BY month
    """)
    if len(monthly) >= 2:
        st.line_chart(monthly.set_index("month")[["revenue"]])
        st.bar_chart(monthly.set_index("month")[["total_trips"]])
    else:
        st.info("Need trips across at least 2 different months to show a trend. "
                "Add more rows with different trip_date months in the Edit Data tab.")

    st.subheader("Month-over-Month Revenue Growth")
    if len(monthly) >= 2:
        monthly["mom_growth_pct"] = monthly["revenue"].pct_change().round(3) * 100
        st.dataframe(monthly, use_container_width=True, hide_index=True)

    st.subheader("Weekly Cancellation Rate Trend")
    weekly = q(conn, """
        SELECT strftime('%Y-%W', trip_date) AS week,
               ROUND(100.0 * SUM(CASE WHEN trip_status='Cancelled' THEN 1 ELSE 0 END) / COUNT(*), 1) AS cancel_rate_pct
        FROM trips GROUP BY week ORDER BY week
    """)
    if len(weekly) >= 2:
        st.line_chart(weekly.set_index("week")[["cancel_rate_pct"]])

    st.subheader("New Rider Signups by Month")
    signups = q(conn, """
        SELECT strftime('%Y-%m', signup_date) AS signup_month, COUNT(*) AS new_riders
        FROM riders GROUP BY signup_month ORDER BY signup_month
    """)
    if not signups.empty:
        st.bar_chart(signups.set_index("signup_month"))

with tab_insights:
    st.subheader("🔍 Key Insights")
    st.caption("Computed live from the current data — these update automatically as you edit.")

    insight_lines = []  # also feeds the "Ask the Data" chatbot below

    # Insight 1: cancellation gap by vehicle
    cancel_by_vehicle = q(conn, """
        SELECT d.vehicle_type,
               ROUND(100.0*SUM(CASE WHEN t.trip_status='Cancelled' THEN 1 ELSE 0 END)/COUNT(*), 1) AS cancel_rate_pct
        FROM trips t JOIN drivers d ON t.driver_id = d.driver_id
        GROUP BY d.vehicle_type ORDER BY cancel_rate_pct DESC
    """)
    if len(cancel_by_vehicle) >= 2:
        worst = cancel_by_vehicle.iloc[0]
        best = cancel_by_vehicle.iloc[-1]
        line = (f"{worst['vehicle_type']} trips cancel at {worst['cancel_rate_pct']}%, "
                f"vs. only {best['cancel_rate_pct']}% for {best['vehicle_type']}.")
        insight_lines.append("Cancellation gap: " + line)
        st.markdown(f"**🚨 Cancellation gap:** {line}")

    # Insight 2: revenue concentration (top 20% of riders)
    rider_rev = q(conn, """
        SELECT rider_id, SUM(fare) AS spend FROM trips
        WHERE trip_status='Completed' GROUP BY rider_id ORDER BY spend DESC
    """)
    if len(rider_rev) >= 5:
        top_n = max(1, int(len(rider_rev) * 0.2))
        pct = 100 * rider_rev.head(top_n)["spend"].sum() / rider_rev["spend"].sum()
        line = f"the top 20% of riders ({top_n} of {len(rider_rev)}) generate {pct:.1f}% of total revenue."
        insight_lines.append("Revenue concentration: " + line)
        st.markdown(f"**💰 Revenue concentration:** {line}")

    # Insight 3: surge-hour fare premium
    surge = q(conn, """
        SELECT CASE WHEN CAST(strftime('%H', trip_date) AS INTEGER) IN (8,9,18,19)
                    THEN 'Rush Hour' ELSE 'Off-Peak' END AS period,
               ROUND(AVG(fare/distance_km), 2) AS fare_per_km
        FROM trips WHERE trip_status='Completed' GROUP BY period
    """)
    if len(surge) == 2:
        rush = surge[surge.period == "Rush Hour"]["fare_per_km"]
        off = surge[surge.period == "Off-Peak"]["fare_per_km"]
        if not rush.empty and not off.empty and off.iloc[0] > 0:
            premium = 100 * (rush.iloc[0] - off.iloc[0]) / off.iloc[0]
            line = (f"rush-hour trips cost {premium:.0f}% more per km than off-peak "
                    f"(₹{rush.iloc[0]} vs ₹{off.iloc[0]}).")
            insight_lines.append("Surge premium: " + line)
            st.markdown(f"**⏰ Surge premium:** {line}")

    # Insight 4: revenue trend
    if len(monthly) >= 2:
        first, last = monthly.iloc[0], monthly.iloc[-1]
        if first["revenue"] > 0:
            growth = 100 * (last["revenue"] - first["revenue"]) / first["revenue"]
            direction = "grew" if growth >= 0 else "declined"
            line = f"revenue {direction} {abs(growth):.0f}% from {first['month']} to {last['month']}."
            insight_lines.append("Revenue trend: " + line)
            st.markdown(f"**📈 Revenue trend:** {line}")

    st.divider()
    st.caption(
        "Each callout above is generated from a live SQL query, not hardcoded — "
        "edit the data and these will change too. Good talking point for interviews: "
        "these are the kind of 'so what' statements that turn a query into an insight."
    )

with tab_chat:
    st.subheader("💬 Ask the Data")
    st.caption(
        "Chat with an AI (via Groq) about what's in the dashboard right now — "
        "it's given the current KPIs and insights as context, not the raw 500 rows."
    )

    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    # Build a compact, current-data context string for the system prompt.
    data_context = (
        f"Total trips: {int(summary['total_trips'])}. "
        f"Completed: {int(completed)}. Cancellation rate: {cancel_rate}%. "
        f"Total revenue: ₹{summary['total_revenue']:,.0f}. "
        f"Avg fare per km: ₹{fare_per_km}.\n"
        + ("\n".join(insight_lines) if insight_lines else "No additional insights available yet.")
    )

    system_prompt = (
        "You are a helpful data analyst explaining a ride-sharing analytics dashboard "
        "to someone non-technical. Use plain English, keep answers short (3-5 sentences "
        "unless asked for more detail), and only use the data given below — don't invent "
        "numbers that aren't in it. If asked something the data can't answer, say so.\n\n"
        f"Current dashboard data:\n{data_context}"
    )

    col_a, col_b = st.columns([3, 1])
    with col_b:
        if st.button("✨ Explain these insights"):
            st.session_state.chat_history.append(
                {"role": "user", "content": "Explain what's going on in this data in plain English."}
            )
    with col_a:
        st.caption("Type a question below, or click the button for a quick summary →")

    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    user_question = st.chat_input("Ask something about the data...")
    if user_question:
        st.session_state.chat_history.append({"role": "user", "content": user_question})

    # If the last message is from the user and hasn't been answered yet, call Groq.
    if st.session_state.chat_history and st.session_state.chat_history[-1]["role"] == "user":
        with st.chat_message("user"):
            st.markdown(st.session_state.chat_history[-1]["content"])
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                messages = [{"role": "system", "content": system_prompt}] + st.session_state.chat_history
                reply, error = call_groq(messages)
                if error:
                    st.warning(error)
                else:
                    st.markdown(reply)
                    st.session_state.chat_history.append({"role": "assistant", "content": reply})

    if st.session_state.chat_history:
        if st.button("🗑️ Clear chat"):
            st.session_state.chat_history = []
            st.rerun()

with tab_raw:
    st.subheader("Run Your Own Query")
    st.caption("Try any SELECT statement against the riders / drivers / trips tables.")
    default_query = "SELECT * FROM trips LIMIT 10;"
    user_sql = st.text_area("SQL query", value=default_query, height=100)
    if st.button("Run query"):
        try:
            result = q(conn, user_sql)
            st.dataframe(result, use_container_width=True, hide_index=True)
        except Exception as e:
            st.error(f"Query error: {e}")

    st.subheader("Current Tables")
    st.write("**Riders**")
    st.dataframe(q(conn, "SELECT * FROM riders"), use_container_width=True, hide_index=True)
    st.write("**Drivers**")
    st.dataframe(q(conn, "SELECT * FROM drivers"), use_container_width=True, hide_index=True)
    st.write("**Trips**")
    st.dataframe(q(conn, "SELECT * FROM trips"), use_container_width=True, hide_index=True)

st.divider()
st.caption(
    "Built with Streamlit + SQLite (in-memory). Edit data in the ✏️ Edit Data tab — "
    "everything updates live, using the same KPI logic as ride_sharing_analytics.sql."
)
